### ISSUE TITLE
Too many items error for playlist with 1,401 songs

### ISSUE THREAD

**Issue by briankaemingk** [sigma67/spotifyplaylist_to_gmusic#1]
Hi, thanks for this project!! I tried transfer [a very large playlist](https://open.spotify.com/playlist/5I5VBP5DVLbJJnpyw0Nm3q), with 1,401 songs. It processed 1,000 songs successfully, then responded with the following error..
```
{"response_code":"TOO_MANY_ITEMS"}
```

**Comment by sigma67** [comment]
Hey, this is a limitation of Google Play Music. It's not possible to add more than 1,000 items to a playlist.

Possible workarounds would be to 

- warn the user that only the first 1,000 items will be added
- create multiple playlists with names like [Part 1], [Part 2], etc.

**Comment by sigma67** [comment]
YouTube Music supports up to 5000 items in a playlist, so I will close this.
