### ISSUE TITLE
Program says playlist created succesfully but it doesn't show up on the account

### ISSUE THREAD

**Issue by yesn314** [sigma67/spotifyplaylist_to_gmusic#5]
Exactly what the title said. I did setup all correctly and when I refresh my account there is no new playlist.

**Comment by sigma67** [comment]
Google Play Music or YouTube Music? YouTube Music should give you a link in the console. It's normal if it takes a bit to show up in your library.

**Comment by yesn314** [comment]
How do you even select Youtube Music? I don't get a link or anything. It doesn't show up in either Google Play Music or Youtube Music.

**Comment by sigma67** [comment]
You just use `YouTube.py` instead. For Google Play Music it should work fine, although I've had some issues last week as well. I just tried again and it worked. Might be related to the service being phased out?

**Comment by yesn314** [comment]
First of all thanks for the quick response man!
I just did the setup all over again to make sure I didn't do anything weird. I use the mobile client and when I use Youtube.py it gives me this:

Failed loading provided credentials. Make sure to provide a string or a file path. Reason: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "Youtube.py", line 185, in <module>
    main()
  File "Youtube.py", line 132, in main
    ytmusic = YTMusicTransfer()
  File "Youtube.py", line 15, in __init__
    self.api = YTMusic(settings['youtube']['headers'])
  File "C:\Users\Y\anaconda3\envs\downloading\lib\site-packages\ytmusicapi\ytmusic.py", line 96, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
AttributeError: 'YTMusic' object has no attribute 'headers'

Furthermore the spotify link to a playlist is slightly different for me. It's now in the format: https://open.spotify.com/playlist/0C6fLU4LJdh9zNPbys80gi?si=kpOCsjzzRNyxMR8lSUtD. Is this a problem?

**Comment by sigma67** [comment]
The link is fine. Did you run the Youtube setup too? You should have 

```
[youtube]
headers = (long JSON string)
```

in your settings.ini.

**Comment by yesn314** [comment]
Okay that clarifies a lot. I currently have: 
[youtube]
headers = headers_json_from_browser

So how do I run the Youtube setup?

**Comment by sigma67** [comment]
Just run `python3 setup.py youtube`. Then you need to find a request in your browser where you can copy your cookie, as explained here: https://ytmusicapi.readthedocs.io/en/latest/setup.html#authenticated-requests

**Comment by yesn314** [comment]
Ok that was very useful. I didn't spot that before. I read the setup and guide multiple times and it wasn't there.
Anyway it now gives the link, but the link doesn't work. It says: (something has gone wrong). Here is the link in case you're curious:
https://music.youtube.com/playlist?list=PLhqnedN22Vhw8kLXLYF2lZOU4rVTYNiCf

**Comment by sigma67** [comment]
Huh, that is strange. What playlist are you trying to convert? I can try for you to check it works. Else it's hard to tell what might be the cause.

**Comment by yesn314** [comment]
https://open.spotify.com/playlist/0C6fLU4LJdh9zNPbys80gi?si=q-P3A5TgRTWgXxT7deLNhA

Relatively small playlist without errors

**Comment by yesn314** [comment]
Okay good news. The one I made earlier is now showing up. I guess it just takes a really long time. But it's flawless! Thank you so much for making this tool. I don't know why the guys from spotdl aren't using this. I know I will for sure. Now I am gonna write some code to apply metadata and apply covers.

**Comment by sigma67** [comment]
Glad you found it useful and got it working!

> I don't know why the guys from spotdl aren't using this

Feel free to let them know about it :)

**Comment by yesn314** [comment]
Just did :) You don't know how happy I am to finally have some more accurate results. For example for a 300 song playlist it only gets 30 not founds. With spotdl it was the other way around, it only found 30 accurately. If you have very popular music spotdl will work 90% of the time, but not for me. Again thanks!
